In [5]:
import sys

python_path = ['/home/claudio/.local/lib64/python3.6/site-packages','/home/sebastian/.local/lib64/python3.6/site-packages','/home/sebastian/.local/lib/python3.6/site-packages','/home/sebastian/.local/lib/python3.6/site-packages/opencv-4.1.0-py3.6.egg/cv2',
               '/home/sebastian/.local/lib/python3.6/site-packages/cv2','/home/sebastian/dat/onnx/onnx-tensorrt/third_party/onnx']
sys.path.extend(python_path)
from  mat4py import loadmat
import numpy as np

In [6]:
sun_att = loadmat('att_splits.mat')

In [7]:
sun_att.keys()

dict_keys(['allclasses_names', 'att', 'original_att', 'test_seen_loc', 'test_unseen_loc', 'train_loc', 'trainval_loc', 'val_loc'])

In [25]:
att_names = np.array(sun_att['allclasses_names'])
att_names = [a[0] for a in att_names]

In [9]:
equivalents = {'ballroom':['ballroom'], 'bar_lounge': ['bar'], 'bathroom':['bathroom'], 'beach':['beach'], 'breakfast':['hotel_breakfast_area'], 'city_view':['city', 'downtown', 'street', 'tower'], 
              'golf_course':['golf_course'], 'guest_room':['bedroom'], 'health_club':['gymnasium_indoor'], 'hotel_front':['hotel_outdoor','factory_outdoor','skyscraper'],
              'kitchen':['kitchen','kitchenette'], 'living_room':['living_room'], 'lobby_view':['lobby','landing','reception'], 'meeting_room':['auditorium'], 'natural_view':['mountain','mountain_path', 'mountain_road','mountain_snowy'],
              'pool_view':['swimming_pool_outdoor'], 'restaurant':['restaurant']}

In [29]:
categories = list(equivalents.keys())

In [10]:
len(equivalents.keys())

17

In [17]:
attributes = sun_att['att']

In [18]:
import numpy as np
import pandas as pd

In [19]:
attributes = np.array(attributes)

In [20]:
attributes = attributes.T

In [21]:
attributes.shape

(717, 102)

In [26]:
final_att = []
for k in equivalents.keys():
    l = equivalents[k]
    t = np.isin(att_names, l)
    att = attributes[t]
    mean = att.mean(axis=0)
    final_att.append(mean)

In [27]:
final_attributes = np.array(final_att)

In [28]:
final_attributes.shape

(17, 102)

In [113]:
semantic = pd.read_pickle('semantic_embeddings.pkl')

In [31]:
df = pd.DataFrame(final_attributes)

In [32]:
df['Class'] = categories

In [33]:
df.to_pickle('sun_attributes.pkl')

In [34]:
df

,0,1,2,3,4,5,6,7,8,9,...,93,94,95,96,97,98,99,100,101,Class
0,0.000000,0.000000,0.000000,0.000000,0.000000,0.126915,0.000000,0.000000,0.000000,0.042305,...,0.359592,0.000000,0.063457,0.042305,0.031729,0.010576,0.000000,0.063457,0.021152,ballroom
1,0.000000,0.000000,0.000000,0.000000,0.000000,0.068608,0.000000,0.000000,0.000000,0.098011,...,0.460652,0.000000,0.029403,0.049005,0.000000,0.117613,0.019602,0.039204,0.019602,bar_lounge
2,0.000000,0.000000,0.000000,0.000000,0.000000,0.010863,0.000000,0.000000,0.000000,0.076042,...,0.510568,0.000000,0.043453,0.054316,0.021726,0.010863,0.000000,0.065179,0.010863,bathroom
3,0.306280,0.000000,0.000000,0.011344,0.249561,0.164484,0.028359,0.022687,0.051047,0.056718,...,0.022687,0.073734,0.000000,0.028359,0.011344,0.000000,0.000000,0.113437,0.000000,beach
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.058658,0.000000,0.008380,0.000000,0.226253,...,0.360328,0.000000,0.058658,0.083797,0.000000,0.041899,0.000000,0.083797,0.000000,breakfast
5,0.033886,0.134925,0.102026,0.101016,0.002565,0.115465,0.000000,0.012591,0.009912,0.002430,...,0.146048,0.007079,0.305088,0.081173,0.023855,0.005052,0.004054,0.018917,0.021066,city_view
6,0.038471,0.006412,0.019236,0.006412,0.096178,0.102589,0.179531,0.019236,0.224414,0.019236,...,0.064118,0.019236,0.012824,0.012824,0.019236,0.000000,0.000000,0.121825,0.000000,golf_course
7,0.000000,0.000000,0.000000,0.000000,0.000000,0.085625,0.000000,0.000000,0.000000,0.294931,...,0.437639,0.000000,0.019028,0.028542,0.009514,0.009514,0.000000,0.247361,0.000000,guest_room
8,0.000000,0.000000,0.000000,0.000000,0.000000,0.009604,0.000000,0.009604,0.000000,0.000000,...,0.509004,0.000000,0.067227,0.028812,0.000000,0.028812,0.000000,0.019208,0.019208,health_club
9,0.013262,0.116429,0.062086,0.020838,0.006773,0.119057,0.000000,0.023778,0.006851,0.007071,...,0.180198,0.006631,0.274382,0.092716,0.021058,0.000000,0.003458,0.010529,0.013689,hotel_front
10,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.041731,...,0.466549,0.000000,0.058900,0.058542,0.005485,0.021223,0.005485,0.036961,0.005485,kitchen
11,0.000000,0.000000,0.000000,0.000000,0.000000,0.037176,0.000000,0.000000,0.000000,0.315996,...,0.408935,0.000000,0.027882,0.037176,0.000000,0.027882,0.000000,0.334583,0.000000,living_room
12,0.000000,0.000000,0.000000,0.000000,0.000000,0.077987,0.000000,0.020820,0.000000,0.052031,...,0.457100,0.000000,0.083241,0.109237,0.041601,0.000000,0.005215,0.078183,0.010351,lobby_view
13,0.000000,0.000000,0.000000,0.000000,0.000000,0.017638,0.000000,0.052915,0.000000,0.088192,...,0.432142,0.000000,0.035277,0.176384,0.061735,0.000000,0.000000,0.035277,0.061735,meeting_room
14,0.023754,0.089632,0.097884,0.045591,0.001676,0.063313,0.209900,0.298672,0.092659,0.000000,...,0.089156,0.258490,0.026936,0.013532,0.022865,0.001676,0.019119,0.083601,0.003549,natural_view
15,0.027308,0.000000,0.006827,0.000000,0.238943,0.197981,0.000000,0.027308,0.006827,0.095577,...,0.129712,0.020481,0.027308,0.054615,0.013654,0.000000,0.000000,0.150193,0.000000,pool_view
16,0.000000,0.000000,0.000000,0.000000,0.000000,0.044570,0.000000,0.008914,0.000000,0.062398,...,0.392217,0.000000,0.053484,0.044570,0.008914,0.044570,0.000000,0.089140,0.008914,restaurant

In [40]:
t = np.isin(att_names, 'restaurant')

In [41]:
attributes[t]

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.04457008, 0.        , 0.00891402, 0.        , 0.06239811,
        0.00891402, 0.03565606, 0.        , 0.        , 0.        ,
        0.        , 0.37438866, 0.        , 0.30307653, 0.19610834,
        0.04457008, 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.00891402, 0.        , 0.        , 0.        ,
        0.        , 0.08914016, 0.        , 0.        , 0.02674205,
        0.        , 0.        , 0.00891402, 0.00891402, 0.        ,
        0.        , 0.        , 0.02674205, 0.        , 0.        ,
        0.        , 0.04457008, 0.        , 0.        , 0.00891402,
        0.02674205, 0.01782803, 0.07131212, 0.00891402, 0.00891402,
        0.04457008, 0.26742047, 0.02674205, 0.05348409, 0.14262425,
        0.00891402, 0.        , 0.        , 0.06239811, 0.16045228,
        0.        , 0.        , 0.        , 0.        , 0.00891402,
        0.        , 0.        , 0.        , 0.00891402, 0.08914016,
        0.00891402, 0.26742047, 0.        , 0.14262425, 0.06239811,
        0.07131212, 0.        , 0.07131212, 0.        , 0.        ,
        0.04457008, 0.        , 0.        , 0.25850645, 0.00891402,
        0.00891402, 0.47244283, 0.00891402, 0.39221669, 0.        ,
        0.05348409, 0.04457008, 0.00891402, 0.04457008, 0.        ,
        0.08914016, 0.00891402]])